#ifndef FLASH_LAYOUT_H
#define FLASH_LAYOUT_H

#include "w25q128.h"

#define FLASH_LAYOUT_STATE_OFFSET 0u
#define FLASH_LAYOUT_STATE_SIZE (1024u * 1024u)
#define FLASH_LAYOUT_ROMPACK_OFFSET (FLASH_LAYOUT_STATE_OFFSET + FLASH_LAYOUT_STATE_SIZE)
#define FLASH_LAYOUT_ROMPACK_SIZE (W25Q128_SIZE_BYTES - FLASH_LAYOUT_ROMPACK_OFFSET)

#endif
